name: Docker Build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:

    - name: docker build
      run: |
        docker build -t artgallery .

    - name: docker push
      run: |
        docker push artgallery


          
          


