name: Python Build and Test

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tk
          pip install coverage
      - name: Test and display coverage
        run: |
          coverage run -m unittest discover
          coverage report -m


      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          docker build -t artgallery: .
          docker tag artgallery docker.pkg.github.com/JeffreyCarson/DevOpsArtGalleryIntegration/artgallery

      - name: Push Docker image to GitHub Packages
        run: docker push docker.pkg.github.com/JeffreyCarson/DevOpsArtGalleryIntegration/artgallery
      

          